### ISSUE TITLE
Change button hover states

### ISSUE THREAD

**Issue by afhill** [nextgentravel/travel-guidebook#2]
@potatowave - The contrast on button hover states isn't enough. instead of changing the font color, can you change the background of the button to hex 002D42 and keep the font color the same?

Current: 
<img width="345" alt="Travel_Guidebook" src="https://user-images.githubusercontent.com/12671696/65795896-58c1eb80-e139-11e9-8aa8-63b66380509a.png" border="1">

**Comment by potatowave** [comment]
@afhill I changed the hover to 002D42.  The text looked super dark so I changed text to FFFFFF.

Please review at let me know.

These inconsistencies are from overriding Aurora to implement the colours in our design.

**Comment by afhill** [comment]
💯 - thanks!
